package com.example.rag.model;

import lombok.Data;
import java.util.List;
import java.util.Map;

/**
 * Represents the response from the RAG system.
 * Contains the answer to the question along with supporting documents
 * and hallucination detection information.
 */
@Data
public class RagResponse {
    /**
     * The original question that was asked
     */
    private String question;

    /**
     * The answer generated by the RAG system
     */
    private String answer;

    /**
     * Details about potential hallucinations in the generated answer
     */
    private HallucinationDetails hallucination;

    /**
     * List of documents used to generate the answer
     */
    private List<Map<String, Object>> docs;
}
